FROM node:22-alpine AS base
RUN corepack enable && corepack prepare pnpm@11.3.0 --activate
RUN npm install -g bun

FROM base AS deps
WORKDIR /app
COPY package.json bun.lock pnpm-lock.yaml pnpm-workspace.yaml ./
RUN bun install --frozen-lockfile

FROM base AS runner
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
ENV NODE_ENV=development
ENV NEXT_TELEMETRY_DISABLED=1
EXPOSE 3000
ENV PORT=3000
ENV HOSTNAME="0.0.0.0"
CMD ["bun", "run", "dev"]
